# Generated by Django 4.1.2 on 2022-10-06 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eqRentalApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rent',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
